#!/bin/bash

#    Main bash script of the program    
#    Copyright (C) 2021  Player-5

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


function help
{
  echo "auto-update help page"
  echo "-r"
  echo "  Will restart the computer after update is done."
  echo "-s"
  echo "  Will shutdown the computer after update is done."
}

function update
{
  apt-get update &&
  apt-get dist-upgrade -Vy &&
  apt-get autoremove -y &&
  apt-get autoclean &&
  apt-get clean

  if [ "$1" = '-r' ]; then
    shutdown -r now
  elif [ "$1" = '-s' ]; then
    shutdown now
  fi
}

if [ "$1" = '-h' ]; then
  help
else
  update $1
fi
