#!/bin/bash

function help
{
  echo "auto-update help page"
  echo "-r"
  echo "  Will restart the computer after update is done."
  echo "-s"
  echo "  Will shutdown the computer after update is done."
}

function update
{
  apt-get update &&
  apt-get dist-upgrade -Vy &&
  apt-get autoremove -y &&
  apt-get autoclean &&
  apt-get clean

  if [ "$1" = '-r' ]; then
    shutdown -r now
  elif [ "$1" = '-s' ]; then
    shutdown now
  fi
}

if [ "$1" = '-h' ]; then
  help
else
  update $1
fi
